import Image from 'next/image';

export default function Home() {
  return (
    <main className="">
      <section className="flex p-20 gap-16 border justify-center">
        <div>
          <h1 className="text-5xl leading-[3.4rem] mb-2">
            Conheça a <br /> História dos <br /> Computadores
          </h1>
          <p className="text-neutral-500">
            Aprendizado dinâmico e interativo!
          </p>
        </div>
        <div>
          <Image
            className="rounded-lg w-80"
            src="/assets/images/turing-generated-by-ia.jpg"
            alt="Turing generated by IA"
            width={500}
            height={500}
          />
        </div>
      </section>
    </main>
  );
};